import { useState } from "react";
import { Download, FileCheck2, ShieldAlert, ShieldCheck } from "lucide-react";
import { LedgerAPI, apiErrorMessage, api } from "../../lib/api";
import { Button } from "../ui/Button";
import { ErrorBanner, PageSpinner } from "../ui/Feedback";
import { formatDateTime, ledgerActionLabel, truncateHash } from "../../lib/utils";

interface AuditReport {
  reportTitle: string;
  complianceStandard: string;
  generatedAt: string;
  generatedBy: { name: string; role: string };
  caseSummary: {
    caseNumber: string;
    title: string;
    status: string;
    totalDocuments: number;
    verifiedDocuments: number;
  };
  cryptographicIntegrity: {
    chainStatus: string;
    totalLedgerEntries: number;
    brokenIndex: number | null;
    brokenEntryId: number | string | null;
  };
  evidentiaryTrail: Array<{
    seq: number;
    ledgerId: number;
    action: string;
    actorName: string;
    actorRole: string;
    documentTitle: string;
    entryHash: string;
    timestamp: string;
    hasSignature: boolean;
  }>;
}

export function AuditReportPanel({ caseId }: { caseId: string }) {
  const [report, setReport] = useState<AuditReport | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      const res = await api.get(`/cases/${caseId}/audit-report`);
      setReport(res.data.data.report);
    } catch (err) {
      setError(apiErrorMessage(err));
    } finally {
      setLoading(false);
    }
  }

  const isValid = report?.cryptographicIntegrity.chainStatus.includes("VALID");

  return (
    <div className="max-w-3xl">
      <div className="flex items-center justify-between mb-4">
        <div>
          <h3 className="text-[16px] font-semibold text-text-primary">Case audit certificate</h3>
          <p className="text-[13px] text-text-secondary mt-0.5">
            Section 65B / BSA 2023 compliant evidentiary export of the full case ledger.
          </p>
        </div>
        <div className="flex gap-2">
          <Button size="sm" variant="secondary" loading={loading} onClick={generate}>
            {report ? "Refresh" : "Generate report"}
          </Button>
          <a
            href={LedgerAPI.auditReportDownloadUrl(caseId)}
            className="inline-flex items-center gap-1.5 rounded-sm bg-primary px-3 py-1.5 text-[13px] font-medium text-white hover:bg-primary-hover"
          >
            <Download className="h-3.5 w-3.5" />
            Download certificate
          </a>
        </div>
      </div>

      {error && <ErrorBanner message={error} />}
      {loading && <PageSpinner label="Assembling evidentiary trail…" />}

      {report && (
        <div className="flex flex-col gap-4">
          <div
            className={`flex items-center gap-2 rounded-sm border px-4 py-3 ${
              isValid ? "border-secondary/30 bg-secondary/5" : "border-danger/30 bg-danger/5"
            }`}
          >
            {isValid ? (
              <ShieldCheck className="h-5 w-5 text-secondary shrink-0" />
            ) : (
              <ShieldAlert className="h-5 w-5 text-danger shrink-0" />
            )}
            <div>
              <p className={`text-[13px] font-semibold ${isValid ? "text-secondary" : "text-danger"}`}>
                {report.cryptographicIntegrity.chainStatus}
              </p>
              <p className="text-[12px] text-text-secondary">
                {report.cryptographicIntegrity.totalLedgerEntries} ledger entries verified against the
                hash chain
                {!isValid && report.cryptographicIntegrity.brokenEntryId !== null
                  ? ` — break at ledger ID ${report.cryptographicIntegrity.brokenEntryId}`
                  : ""}
              </p>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3 text-[12px]">
            <div className="rounded-sm border border-border bg-surface px-3 py-2.5">
              <p className="text-text-secondary">Case</p>
              <p className="text-text-primary font-medium mt-0.5">
                {report.caseSummary.caseNumber} — {report.caseSummary.title}
              </p>
            </div>
            <div className="rounded-sm border border-border bg-surface px-3 py-2.5">
              <p className="text-text-secondary">Documents</p>
              <p className="text-text-primary font-medium mt-0.5">
                {report.caseSummary.verifiedDocuments} / {report.caseSummary.totalDocuments} verified
              </p>
            </div>
            <div className="rounded-sm border border-border bg-surface px-3 py-2.5">
              <p className="text-text-secondary">Generated by</p>
              <p className="text-text-primary font-medium mt-0.5">
                {report.generatedBy.name} ({report.generatedBy.role})
              </p>
            </div>
            <div className="rounded-sm border border-border bg-surface px-3 py-2.5">
              <p className="text-text-secondary">Generated at</p>
              <p className="text-text-primary font-medium mt-0.5 font-mono-num">
                {formatDateTime(report.generatedAt)}
              </p>
            </div>
          </div>

          <div>
            <p className="text-[12px] font-medium text-text-secondary mb-2 flex items-center gap-1.5">
              <FileCheck2 className="h-3.5 w-3.5" />
              Evidentiary trail ({report.evidentiaryTrail.length})
            </p>
            <div className="rounded-sm border border-border overflow-hidden">
              {report.evidentiaryTrail.map((ev, i) => (
                <div
                  key={ev.ledgerId}
                  className={`px-3 py-2 text-[12px] flex items-center justify-between gap-3 ${
                    i % 2 === 0 ? "bg-surface" : "bg-background"
                  }`}
                >
                  <div className="min-w-0">
                    <span className="font-medium text-text-primary">{ledgerActionLabel(ev.action)}</span>{" "}
                    <span className="text-text-secondary">
                      · {ev.documentTitle} · {ev.actorName} ({ev.actorRole})
                    </span>
                  </div>
                  <span className="font-mono-num text-text-secondary/80 shrink-0">
                    #{ev.ledgerId} · {truncateHash(ev.entryHash, 6)}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
